name: data_persistence
description: Repository to handle Data Persistence related stuff.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  google_maps_flutter: ^2.1.12
  hive: ^2.2.3
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
